### ISSUE TITLE
works with firmware 5.1?

### ISSUE THREAD

**Issue by gramels** [kraih/kefctl#6]
Hi, I would love to use this, is it tested with 5.1 firmware?

**Comment by kraih** [comment]
No, i only have a pair of LS50 Wireless for testing. And the latest firmware for those is still 4.1 from 2019.

**Comment by gramels** [comment]
ok, once I dare to update I will test with my LSX and let you know. Thanks for your code!

**Comment by gramels** [comment]
works with firmware 5.1 on my KEF LSX.
Thanks.
:-)

**Comment by kraih** [comment]
Thanks for letting me know.
