### ISSUE TITLE
Standby 20 minutes

### ISSUE THREAD

**Issue by sstativa** [kraih/kefctl#7]
There is an error in line 83
```elsif ($standby eq '20') { substr $source_bits, 2, 2, '10' }```
should be
```elsif ($standby eq '20') { substr $source_bits, 2, 2, '00' }```

**Comment by kraih** [comment]
Thanks, fixed.

**Comment by kraih** [comment]
Actually, i think that might have been intentionally back when i originally wrote it. The LSX firmware had a bug where they would crash under certain conditions with a 20 minute standby time. Don't remember the details anymore though.
